### ISSUE TITLE
Окно добавления пациента: шрифт и дата рождения

### ISSUE THREAD

**Issue by Bl0ck154** [VyacheslavTretyak/CourseWork#14]
1. Шрифт окна добавления довольно мелковат, особенно это заметно в хедере, так как хедер отличается от главного окна. Желательно выполнять дизайн программы в одном стиле. 
Male Female написано большим шрифтом чем в других полях ввода.
2. Нули не подставляются в день и месяц даты рождения, т.е. нельзя ввести 2.10.2018 , нужно обязательно писать **0**2.10.2018. Предлагаю заменить поле на DateTimePicker.
И еще поле называется Year of birth, правильно - Date of birth.
![default](https://user-images.githubusercontent.com/36800583/46331459-c3bd0d00-c620-11e8-8cb0-a7e75fba725b.png)
В остальном всё отлично, протестировал - всё работает.

**Comment by uatrade** [comment]
Done!
