### ISSUE TITLE
Выравнивание Document Info

### ISSUE THREAD

**Issue by VyacheslavTretyak** [VyacheslavTretyak/CourseWork#15]
Выровнять текст по верхнему краю в поле document's Info в окне Patient Card.

**Comment by MadMks** [comment]
Предлагаю поменять на другие текстбоксы.

**Comment by MadMks** [comment]
Предлагаю поменять немного на другие ТекстАреаБоксы, в которых текст пишется сверху.

Скриншот:
![image](https://user-images.githubusercontent.com/31092702/46376645-2bb23880-c69f-11e8-90ed-48724efb776c.png)


Код:
`<TextBox
    Style="{StaticResource MaterialDesignTextAreaTextBox}"
    Margin="32,0,0,0"
    VerticalAlignment="Top"
    Height="100"
    AcceptsReturn="True"
    TextWrapping="Wrap"
    VerticalScrollBarVisibility="Auto"
    materialDesign:HintAssist.Hint="This is a text area"
    IsEnabled="{Binding Path=IsChecked, ElementName=MaterialDesignTextAreaTextBoxEnabledComboBox}" />`

**Comment by KateGir** [comment]
fixed
![patient card 2018-10-03 23 09 55](https://user-images.githubusercontent.com/40317363/46436489-975cda00-c761-11e8-8c66-8365754d2eff.png)
