### ISSUE TITLE
Двойной клик по документу в Карточке Пациента

### ISSUE THREAD

**Issue by VyacheslavTretyak** [VyacheslavTretyak/CourseWork#17]
Двойной клик по документу из списка документов в Карточке Пациента, должен открывать редактирование документа. Так интуитивнее.

**Comment by MadMks** [comment]
Здесь тоже не согласен. Так как кат главном окне двойным кликом открываем карту пациента, а не редактируем пациента. На окне карта пациента вся информация о документе пациента выводится изначально в окно. Так как у нас одно приложение то двойной клик в таблице должен делать что-то одно или открывать для просмотра или открывать на редактирование. Что-то одно, но не разные действия в каждом окне.

**Comment by VyacheslavTretyak** [comment]
Здесь нет функции открытия, так как отображается выделенный документ. Когда хочеш его открыть для редактирования, по привычке делаеш двойной клик, а когда не сработывает, начинаеш искать кнопку "окрыть". Это же пользователи)

**Comment by VyacheslavTretyak** [comment]
Дайте не айтишнику попользоватся программой и все станет заметно)

**Comment by MadMks** [comment]
Исправлено.
