### ISSUE TITLE
Окно PatientCard отступы

### ISSUE THREAD

**Issue by uatrade** [VyacheslavTretyak/CourseWork#18]
Веденная информация слишком близко к границам окна.
![patientcard](https://user-images.githubusercontent.com/34284693/46395299-8d50c200-c6f4-11e8-9392-c454cc0f1250.jpg)

**Comment by KateGir** [comment]
fixed
![patient card 2018-10-03 22 57 56](https://user-images.githubusercontent.com/40317363/46435820-f4579080-c75f-11e8-8ea0-cea2d97ea2ad.png)
