### ISSUE TITLE
Финальная дата, меньше чем стартовая (добавление документа).

### ISSUE THREAD

**Issue by MadMks** [VyacheslavTretyak/CourseWork#19]
При этом документ создается.
И у него финальная дата меньше чем начальная.

Рекомендовано:
Проверка, чтоб документ не создавался когда финальная дата меньше начальной.

Скриншоты:
![screenshot_50](https://user-images.githubusercontent.com/31092702/46432435-f406c780-c756-11e8-9799-3bcd6a97b83d.png)

![screenshot_51](https://user-images.githubusercontent.com/31092702/46432445-f8cb7b80-c756-11e8-9666-20ed8b020a41.png)

**Comment by warslav** [comment]
исправлено
