### ISSUE TITLE
Edit Patient2

### ISSUE THREAD

**Issue by mitGmailCom** [VyacheslavTretyak/CourseWork#21]
При изменении данных пациента, данные не перезаписываются, а добавляется новый пациент. В итоге в БД существует 2 пациента(отредактированный и оригинал).

**Comment by AdaVarts** [comment]
У меня такой ошибки нет, данные изменяются и в БД 1 пациент.

**Comment by VyacheslavTretyak** [comment]
Два пациента появляется, когда редактируеш того который создается при старте. Когда в базе нет такого пациента, он добавляется(ищет по имени которое изменили)

**Comment by VyacheslavTretyak** [comment]
После тестов я закоментирую Начальную Инициализацию. Вопрос можно закрывать.
