### ISSUE TITLE
Главная страница. Форма поиска. В поле Last name запретить ввод цифр

### ISSUE THREAD

**Issue by KateGir** [VyacheslavTretyak/CourseWork#22]
**Шаги:**
1. Открыть Главную страницу MedicallApp
2. Пройти разделу ввода параметров поиска
3. В поле Last name сделать попытку ввода цифр

**Полученный результат:**
В поле удалось ввести цифры

**Ожидаемый результат:**
Запрет ввода цифр

**Скриншот:**
![medicalapp 2018-10-05 21 51 23](https://user-images.githubusercontent.com/40317363/46554722-d322ab80-c8e9-11e8-8b4a-94e2f3190d66.png)

**Comment by Bl0ck154** [comment]
Стоп, а почему только цифры? 
Символы типа *(%?;№?: тоже нужно запретить?

**Comment by KateGir** [comment]
если копать глубже, то Да спец символы, пробелы вначале строки - тоже нужно запретить

Думаю тире, пробел среди строки,  можно разрешить. Для двойных имен к примеру

**Comment by Bl0ck154** [comment]
Ok. Пробелы вначале не запрещаю, просто делаю trim в обработчике, чтоб не учитывались при поиске.
