### ISSUE TITLE
Главная страница. Форма поиска. Минимальный размер окна

### ISSUE THREAD

**Issue by KateGir** [VyacheslavTretyak/CourseWork#24]
**Шаги:**
1.Открыть Главную страницу MedicallApp
2.Пройти к разделу ввода параметров поиска
3.Сделать максимально маленький размер окна 

**Полученный результат:**
При самом маленьком размере, обрезаются названия полей "Card number", "Year of birth"
(требуется установить минимальный размер окна чуток большим)

**Ожидаемый результат:**
При самом маленьком размере,   все названия полей должны отображаться в полном размере. 

Скриншот:
![medicalapp 2018-10-05 22 24 21](https://user-images.githubusercontent.com/40317363/46556155-6d84ee00-c8ee-11e8-9ee5-771ea45d63a5.png)

**Comment by Bl0ck154** [comment]
fixed.
