### ISSUE TITLE
Окно добавления/изменения пациента. Запретить ввод цифр и символов.

### ISSUE THREAD

**Issue by Bl0ck154** [VyacheslavTretyak/CourseWork#25]
Запретить ввод цифр и символов (кроме **-** и пробела) в поля First name, Middle name, Last name.

![default](https://user-images.githubusercontent.com/36800583/46558237-1afb0000-c8f5-11e8-81ea-934f6969b6bd.png)

**Comment by AdaVarts** [comment]
fixed
