### ISSUE TITLE
Карточка Пациента. Кнопка добавления доступна при незаполненных полях

### ISSUE THREAD

**Issue by KateGir** [VyacheslavTretyak/CourseWork#27]
Шаги:
1.Открыть Карточку пациента
2.Нажать кнопку "Add"

Полученный результат:
Кнопки кликабельны при НЕ заполненых полях

Ожидаемый результат:
Кнопка "Add" НЕ кликабельны при отсутствии всех полей карточки

Скриншот:
![add patient 2018-10-06 10 05 39](https://user-images.githubusercontent.com/40317363/46568627-a9509f80-c950-11e8-89db-71e13aa86ebf.png)

**Comment by VyacheslavTretyak** [comment]
не баг
