### ISSUE TITLE
Карточка Пациента. Запретить  ввод цифр, спецсимволов

### ISSUE THREAD

**Issue by KateGir** [VyacheslavTretyak/CourseWork#28]
**Шаги:**
1.Открыть Форму для редактирования пациента
2. Выполнить ввод цифр спецсимволов в поля: First Name, Last Name, Middle Name

**Полученный результат:**
В поле удалось ввести цифры,спецсимволы

**Ожидаемый результат:**
Запрет ввода цифр, спецсимволов и пробела вначале/конце строки

**Скриншот:**
![2018-10-06 10 19 30](https://user-images.githubusercontent.com/40317363/46568666-59260d00-c951-11e8-83b2-543a869f577c.png)

**Comment by VyacheslavTretyak** [comment]
Дубликат 25-го
