### ISSUE TITLE
Редактирование документа. Запретить ввод пробелов в начале строк

### ISSUE THREAD

**Issue by KateGir** [VyacheslavTretyak/CourseWork#31]
**Шаги:**
1. Открыть окно "Edit Document"
2. В строках "Name", "Info" отредактировать данные так чтобы строка начиналась с пробелов

**Полученный результат:**
Документ сохраняется с пробелами в начале строк в полях "Name", "Info"

**Ожидаемый результат:**
Требуется либо запретить ввод пробелов в начале строк, либо чистить при сохранении

![2018-10-06 11 01 00](https://user-images.githubusercontent.com/40317363/46569007-3c8cd380-c957-11e8-9baf-6ea1f16aa953.png)

**Comment by KateGir** [comment]
Думаю цифры и спецсимволы запрещать не нужно, так как для документов это неактуально

**Comment by VyacheslavTretyak** [comment]
Запрещать не нужно. Нужно использовать метод Trim которы уберёт пробелы при сохранении

**Comment by KateGir** [comment]
fixed
