### ISSUE TITLE
При изменении высоты окна "Карта пациента": прячутся буквы (поле поиска по имени)

### ISSUE THREAD

**Issue by MadMks** [VyacheslavTretyak/CourseWork#36]
Рекомендуется: увеличить минВысоту окна "Карта пациента".

Пример ошибки:
![image](https://user-images.githubusercontent.com/31092702/46570520-1c1c4380-c96e-11e8-81d1-dfab5d3b29fe.png)

**Comment by VyacheslavTretyak** [comment]
У меня всё ок.

**Comment by KateGir** [comment]
Не удается воспроизвести :(
Видео:
https://monosnap.com/file/qExwOxjRaSoOjUTEf1zVnAFkRJ3Czw
