### ISSUE TITLE
Label "Список карточек пациентов:" 

### ISSUE THREAD

**Issue by MadMks** [VyacheslavTretyak/CourseWork#7]
Хочу на это строке (в дизайне, в дальнейшем в проекте) добавить Label "Список карточек пациентов:", чтоб любому пользователю (который соображает и который не дружит логикой) было ясно что отображается в Таблице. 
И на основе этого - будет больше логики в кнопке "Открыть карточку". Будет более понятнее что открывает эта кнопка, и что нужно выбрать "карточку пациента" из таблицы(списка карточек пациентов).

https://github.com/VyacheslavTretyak/CourseWork/blob/6ef1319dc066c91b9319f138d177455d007274ff/MedicalApp/MainWindow.xaml#L69

**Comment by Bl0ck154** [comment]
Сделаем)
