### ISSUE TITLE
Текст в полях ввода на главной странице отображается неправильно

### ISSUE THREAD

**Issue by Bl0ck154** [VyacheslavTretyak/CourseWork#9]
Текст, который обозначает названия полей, отображается неправильно, если окно уменьшено.
То есть, чем больше окно тем правильней этот текст отображается.
Но размер окна не должен влиять на это.

![image](https://user-images.githubusercontent.com/36800583/45880807-dc702c00-bdb1-11e8-8921-46d800cf5d57.png)

![image](https://user-images.githubusercontent.com/36800583/45880705-87341a80-bdb1-11e8-85b4-88b00e6debe6.png)

**Comment by MadMks** [comment]
Для начала давай поменяем FontSize для всего окна с 24 на 14 (24 слишком большой, 14 должен аккуратнее смотреться).
На этой строке:
https://github.com/VyacheslavTretyak/CourseWork/blob/3f3cccf46c86f29c121b1da10c1df843531c5d33/MedicalApp/MainWindow.xaml#L12

Вечером смогу посмотреть что еще исправить.

**Comment by Bl0ck154** [comment]
14 слишком маленький, как по мне. 18-20 думаю нормально будет.
Но это всё равно не решает проблему, что-то не так с `Style="{StaticResource MaterialDesignFloatingHintTextBox}"`

**Comment by Bl0ck154** [comment]
Fixed
